'''
Created on 11 janv. 2012

@author: jglouis
'''

# ======================================================== #
# File automagically generated by GUI2Exe version 0.5.1
# Copyright: (c) 2007-2011 Andrea Gavana
# ======================================================== #

# Let's start with some default (for me) imports...

from cx_Freeze import setup, Executable
import sys, os


# Process the includes, excludes and packages first

path = sys.path + ["engine", "gui", "material", "tool", 'data', 'image']
includes = []
excludes = ['_gtkagg', '_tkagg', 'bsddb', 'curses', 'email', 'pywin.debugger',
            'pywin.debugger.dbgcon', 'pywin.dialogs', 'tcl',
            'Tkconstants', 'Tkinter']
packages = []
includefiles = ['data','image']
path = []

exe = Executable(
    # what to build
    script = "eclipse.py",
    initScript = None,
    base = 'Win32GUI',
    icon = os.path.abspath('image/eclipse.ico')
    #targetDir = r"../dist"
    )

setup(
    
    version = "0.1",
    description = "Eclipse Cx_Freeze Build",
    author = "jglouis",
    name = "cx_Freeze Sample File",
    
    options = {"build_exe": {"path":path,
                             "includes": includes,
                             "excludes": excludes,
                             "packages": packages,
                             "include_files":includefiles
                             }
               },
                           
    executables = [exe]
    )
